on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - uses: maxnowack/action-release-generator@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          branch: asdf
