on:
  workflow_dispatch:
  push:
    tags:
      - '!refs/tags/*'
      - '!*'
      - v*

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - uses: maxnowack/action-release-generator@main
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          branch: asdf
          useNameFromRef: 'true'
          ref: "${{ github.ref }}"
