on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - uses: maxnowack/action-release-generator@main
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
