name: Test

on:
  pull_request:
  push:
    tags:
      - '!refs/tags/*'
      - '!*'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check review app
        id: reviewapp
        run: |
          echo "GIT_REF: $GIT_REF"
          echo "GIT_REF_NAME: $GIT_REF_NAME"
          echo "GIT_HEAD_REF: $GIT_HEAD_REF"
          echo "GIT_BASE_REF: $GIT_BASE_REF"
        env:
          GIT_REF: ${{ github.ref }}
          GIT_REF_NAME: ${{ github.ref_name }}
          GIT_HEAD_REF: ${{ github.head_ref }}
          GIT_BASE_REF: ${{ github.base_ref }}
